version: "3.9"
services:
  api:
    build: .
    container_name: 'movie_api'
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: 'movie_db'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: thpwd
      MYSQL_DATABASE: api_db
    ports:
      - 3306:3306
    volumes:
      - ./docker/data:/docker-entrypoint-initdb.d
